### PR TITLE
Add full support for Argo CD external urls

### PR DESCRIPTION
**Pull request by Hronom**
Enables full support for External URL's in Argo CD. 
Otherwise it will throw error during updating deployment status.

I'm not go developer(but java), please check if it ok from go perspective.
I'm providing my verbal approve to edit this PR by maintainers in order to merge it as fast as possible.
Thanks!

### CODE REVIEW

**Comment by Hronom** [comment]
cc @int128

**Comment by int128** [comment]
📝 https://argo-cd.readthedocs.io/en/stable/user-guide/external-url/
https://github.com/argoproj/argo-cd/blob/f0b03071fc00fd81433d2c16861c193992d5a093/common/common.go#L178-L186

**Comment by Hronom** [comment]
Keep in mind that official docs not reflect real useful functionality that they support in source https://github.com/argoproj/argo-cd/blob/f0b03071fc00fd81433d2c16861c193992d5a093/common/common.go#L186 I added comment in proposed changes about it

**Review by int128 — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
