### PR TITLE
Support Manifest Paths annotation when determining related pull requests

### PR DESCRIPTION
**Pull request by quentinplessis**
## Overview

Argo CD defines [argocd.argoproj.io/manifest-generate-paths](https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#webhook-and-manifest-paths-annotation) annotation to specify the paths that are used to generate an application's manifest.

> The argocd.argoproj.io/manifest-generate-paths contains a semicolon-separated list of paths within the Git repository that are used during manifest generation.

This pull request takes into account that annotation to determine more accurately whether a pull request is related to an application event and thus whether a comment should be made or not. 

## Use case

This is useful when manifests are generated based on files from different folders.
Here is an example of a mono-repository folder structure illustrating such a use case:
```
.
├── applications              # contains application settings independent of cluster
│   ├── application-a
│   │   └── common-a.yaml
│   └── application-b
│       └── common-b.yaml
└── clusters                  # contains application settings specific to cluster
    ├── development
    │   ├── application-a
    │   │   └── file1.yaml
    │   └── application-b
    │       └── file2.yaml
    └── production
        ├── application-a
        │   └── file3.yaml
        └── application-b
            └── file4.yaml
```

Here is `application-a`'s development cluster definition

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .;/clusters/development/application-a
  name: application-a
spec:
  destination:
    namespace: my-namespace
    server: https://kubernetes.default.svc
  source:
    path: applications/application-a
    repoURL: https://github.com/user/repo
 ```

`application-a`'s manifest is generated based on files from `applications/application-a` and `clusters/development/application-a` folders.
Without taking the annotation into account, a pull request modifying only `clusters/development/application-a` files is not considered related to `application-a`.

### CODE REVIEW

**Comment by quentinplessis** [comment]
@MatthiasWinzeler Glad this would be of use for you too !

@int128 Could you let me know how to proceed in order to merge this feature ?

**Review by int128 — APPROVED** [review]
Thank you for your great contribution 🎉

**Comment by int128** [comment]
It would be nice if there are some tests for `isPullRequestRelatedToEvent()`. I will try it.

**Comment by MatthiasWinzeler** [comment]
@int128 Many thanks for sacrificing time on your weekend to make this work 🙏 

I tested it by using `ghcr.io/int128/argocd-commenter:pr-663` and it worked successfully!

If someone stumbles upon this in the future, this is the `Application` configuration that works for us as tanka users:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    # we have shared libs in /lib and vendored dependencies in /vendor, so we specify those as well
    argocd.argoproj.io/manifest-generate-paths: /lib;/vendor;environments/podinfo/sandbox
...
spec:
  destination:
    namespace: podinfo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    plugin:
      env:
      - name: TK_ENV_DIR
        value: environments/podinfo/sandbox
      name: tanka
    repoURL: git@github.com:....git
    targetRevision: HEAD
```

Do you plan to create a new release soon? Then we could consume it from that tag instead of the PR-tag.

**Comment by int128** [comment]
No problem. 
I just released the new version.
Could you try it out?

**Comment by quentinplessis** [comment]
I tried it as well, works as expected, thank you!

**Pull request merged**
